---
- name: Move docker-compose.yml to remote host
  template: src=docker-compose.yml.j2 dest={{ deploy_dir }}/docker-compose.yml

- name: Login to private GitLab registry
  docker_login:
    registry_url: "{{ lookup('env', '$CI_REGISTRY') }}"
    username: "{{ lookup('env', '$CI_REGISTRY_USER') }}"
    password: "{{ lookup('env', '$CI_JOB_TOKEN') }}"
#    registry_url: registry.gitlab.com
#    username: gitlab+deploy-token-12980
#    password: NnKYqna3-113b4gex9-X
#    email: oozy.waters@gmail.com

- name: Run docker-compose
  docker_service:
    project_src: '{{ deploy_dir }}'
