---
- name: Move docker-compose.yml to remote host
  template: src=docker-compose.yml.j2 dest={{ deploy_dir }}/docker-compose.yml
  register: template_output

- name: Show templating results
  debug: msg="{{ lookup('template', 'docker-compose.yml.j2') }}"

- name: Login to private GitLab registry
  docker_login:
#    registry_url: "{{ lookup('env', '$CI_REGISTRY') }}"
#    username: "{{ lookup('env', '$CI_REGISTRY_USER') }}"
#    password: "{{ lookup('env', '$CI_JOB_TOKEN') }}"
    registry_url: registry.gitlab.com
    username: gitlab+deploy-token-12980
    password: NnKYqna3-113b4gex9-X
    email: oozy.waters@gmail.com

#- name: Stop and remove all docker container/images
#  script: script.sh

- name: Pull app image
  docker_image:
    name: registry.gitlab.com/oozywaters/qna:latest
    tag: latest

- name: Run application
  docker_container:
    name: qna
    image: registry.gitlab.com/oozywaters/qna
    env:
      APP_SECRET_KEY_BASE: "{{ lookup('env', 'APP_SECRET_KEY_BASE') }}"
      APP_DB_NAME: "{{ lookup('env', 'APP_DB_NAME') }}"
      APP_DB_USERNAME: "{{ lookup('env', 'APP_DB_USERNAME') }}"
      APP_DB_PASSWORD: "{{ lookup('env', 'APP_DB_PASSWORD') }}"
      APP_SMTP_LOGIN: "{{ lookup('env', 'APP_SMTP_LOGIN') }}"
      APP_SMTP_PASSWORD: "{{ lookup('env', 'APP_SMTP_PASSWORD') }}"
    links:
      - db
    ports:
      - "80:80"

- name: Run migrations
  command: docker exec -i qna bash -c 'rake db:migrate 2>/dev/null || rake db:setup'

#- name: Add container to inventory
#  add_host:
#    name: qna
#    ansible_connection: docker
#  changed_when: false
#
#- name: Run migrations
#  deledate_to: qna
#  command: rake db:migrate

#- name: Run docker-compose
#  docker_service:
#    project_src: '{{ deploy_dir }}'
#    remove_orphans: true
#
#- name: 'Migrations: run'
#  run_once: true
#  docker_container:
#    name: 'qna'
#    image: 'registry.gitlab.com/oozywaters/qna:latest'
#    state: started
#    detach: false
#    command: 'rake db:setup'
#    env:
#      APP_SECRET_KEY_BASE: "{{ lookup('env', 'APP_SECRET_KEY_BASE') }}"
#      APP_DB_NAME: "{{ lookup('env', 'APP_DB_NAME') }}"
#      APP_DB_USERNAME: "{{ lookup('env', 'APP_DB_USERNAME') }}"
#      APP_DB_PASSWORD: "{{ lookup('env', 'APP_DB_PASSWORD') }}"
#  changed_when: false
#
#- name: Run docker-compose
#  command: docker-compose -f {{ deploy_dir }}/docker-compose.yml up -d
