---
- name: Move docker-compose.yml to remote host
  template: src=docker-compose.yml.j2 dest={{ deploy_dir }}/docker-compose.yml
  register: template_output

- name: Show templating results
  debug: msg="{{ lookup('template', 'docker-compose.yml.j2') }}"

- name: Login to private GitLab registry
  docker_login:
#    registry_url: "{{ lookup('env', '$CI_REGISTRY') }}"
#    username: "{{ lookup('env', '$CI_REGISTRY_USER') }}"
#    password: "{{ lookup('env', '$CI_JOB_TOKEN') }}"
    registry_url: registry.gitlab.com
    username: gitlab+deploy-token-12980
    password: NnKYqna3-113b4gex9-X
    email: oozy.waters@gmail.com

#- name: Stop and remove all docker container/images
#  script: script.sh

- name: Run docker-compose
  docker_service:
    project_src: '{{ deploy_dir }}'
    remove_orphans: true
    debug: yes

- name: 'Migrations: run'
  run_once: true
  docker_container:
    name: 'qna'
    image: 'registry.gitlab.com/oozywaters/qna:latest'
    state: started
    detach: false
    command: 'rake db:setup'
  changed_when: false
#
#- name: Run docker-compose
#  command: docker-compose -f {{ deploy_dir }}/docker-compose.yml up -d
