stages:
  - build
  - release

#variables:
#  SSH_PRIVATE_KEY: |
#    -----BEGIN RSA PRIVATE KEY-----
#    MIIEpQIBAAKCAQEA0lsqwzejwoiRjhY1tzoSfFiElN1AZvcxIvsaICTBsEWB5ZVM
#    A6Owp0cn5O+i4FWUQfboex00ziIF8fU14yOA4aWjaiJ6B45p1De81jKfXV24nqbV
#    tsifj1H3+UZoO1S0wM9+tw5LVFNmCAK7kylIgskJDdyAXDQIUWxpWAizUcHAQAx4
#    szMBn/t3AM36Emxz/r8uEA3QhFAl+drMWQgXxPiT38x0km2N8RKTItU9i9USQQfi
#    INJs8E65p9EqCcfrztKfgm/CTQrLWlBfqUFk+dtzhDYjQ4DW2qSAwqpXmHgO1gap
#    aGEB7LnpRDlFCHd40WONlvIudTGM3hcI0y9nxQIDAQABAoIBAQCRQ0W3g8/Bgd/K
#    GApGGoMzfUkpJ9TWhfNXrcFv2xIqMQWvzjas+Lf//EJPdTCr7E0ydFg81IFnq9Uh
#    Lm1lClpw+Jptq5tLZowsccUkwdaNejAI1zsUO1z8cuVkLbvC5Q7hayidLvDULbdy
#    5rgzurmJH1zyRogZpBDucYgZtABo/rqiTU80jB4X04GItwMR09eJIMvE7zq2/h0/
#    fm9a/3DZWOGF9JbwMB1vgDDeGOFh6PMvrzkVMBoZAJvEiuOrABnf+Cusgu7XKgCe
#    kpbtTLj43lC8Ee4Rbir8pvz6ntQjoU06LG9ZOgGjEBBm52l16fDbNMAsz+z6/pdh
#    /7WWom9hAoGBAPyx9QVKMbjcBiJ7FWcq/HvK9MBhyDdu0QSQYdNLHn+FCXkS3yiV
#    2zrjPf7VMzjoAUgLvFct8gv/gpckTvtn5guuk6o9QVBsA1LVWLmUnDa5qEsH4ys2
#    H0lBnbRs4qyYAxyGT4L/UtztsTEsXLXpkvTZ2OisKYNTwmIUC1M2Gh3pAoGBANUb
#    dKJvJW//9cCbaqN+53rTBY03vPiJnay5fJl+x4mMqsYd4K7pAsSj8PZDKIdqarCk
#    eoQv0ch3gUP9DyMqxeBIsLPjORJSYeGU31y6CM78I2Dm+DVShSiw5E5xwi1CTXhU
#    g52YtE1A9SOYxT8IbZZOBYrqkX7OWk8m7pYFB0V9AoGBAPuG349eZNPPHsQfpBRH
#    M369bJY6PqL+yUsztEwvj7H66Iz9fefWEpwxKbqI2S2hsfTWyag1caMDuCdd2shg
#    iRnDsfRYeLTmbwB6oJBJHp1Se/QDa9nNS6MNjz7Sy2ZlAWPZRTftkbubVS7PK5Ff
#    aAoU9dXT2JaCPxCFRyiSx7hRAoGAEsWpX4mk5ZnJfx7xpNdP8rzV91ualNYigo2Q
#    UUEeuJogjPUizqWN7d53ImpGDq+sGEVU2YIQ27TTOTb4d2OULK6aii4Q3/FL2AAy
#    MMvebMU/JJET+jZ7rlrusY5JyYzWoCvpsB88erWnImyZq3TFmoDi8hq5mE77G4/V
#    Ynes7U0CgYEAwWe2tCR8LjvlBak+1rBKTDm1ZTTwqaKYzgOU+qc2+cN/oDxiin0U
#    nzhBflRQfVCe97h6O3o+KKFDEWE2SgZTgAqf1wO/MDCJHt8JIzNZ6V4VPdijKTlV
#    0nVdOwVxUNoBtzxV3rAM/IlP7pUUcPeYAhF+hRCxjp9+bTy38TCmKT8=
#    -----END RSA PRIVATE KEY-----
#  APP_SECRET_KEY_BASE: 8a1cef5534b21e32837e692aaf0e8d0973f13454b656dd172413aefeba9f209976a5fb44694ec0262e8e6e7a5c78353801103f9881c118a1457962c1a6bfff5d
#  APP_DB_NAME: qna_production
#  APP_DB_USERNAME: postgres
#  APP_DB_PASSWORD: '123456'
#  CI_REGISTRY_USER: gitlab+deploy-token-12980
#  CI_JOB_TOKEN: NnKYqna3-113b4gex9-X
#  CI_REGISTRY: registry.gitlab.com

build:
  stage: build
  image: docker:stable
  only:
    - master
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - cp config/database.sample.yml config/database.yml
    - cp config/secrets.sample.yml config/secrets.yml
  script:
    - docker build -t registry.gitlab.com/oozywaters/qna .
    - docker push registry.gitlab.com/oozywaters/qna

deploy_app:
  stage: release
  only:
    - master
  tags:
    - ansible
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H '142.93.133.29' >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - 'ansible-playbook ./ansible/deploy.yml -i ./ansible/hosts -vv'
