stages:
  - setup
  - release

before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_rsa
  - ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
  - ssh-keyscan -H '188.166.76.15' >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

provision:
  stage: setup
  only:
    - master
  tags:
    - ansible
  script:
    - 'ansible-playbook ./ansible/provision.yml -i ./ansible/hosts'

deploy_app:
  stage: release
#  variables:
#    CI_DEBUG_TRACE: "true"
  only:
    - master
  tags:
    - ansible
  script:
    - 'ansible-playbook ./ansible/deploy.yml -i ./ansible/hosts'
