stages:
  - build
  - release

build:
  stage: build
  image: docker:stable
  only:
    - master
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - cp config/database.sample.yml config/database.yml
  script:
    - docker build -t registry.gitlab.com/oozywaters/qna .
    - docker push registry.gitlab.com/oozywaters/qna

deploy_app:
  stage: release
  only:
    - master
  tags:
    - ansible
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H '142.93.133.29' >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - 'ansible-playbook ./ansible/deploy.yml -i ./ansible/hosts'
