stages:
  - release

deploy_app:
  stage: release
  variables:
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
  only:
    - master
  tags:
    - ansible
  script:
    - 'ansible-playbook ./ansible/deploy.yml -i ./ansible/hosts'
