stages:
  - release

deploy_app:
  stage: release
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
    - chmod 644 ~/.ssh/known_hosts
  variables:
    CI_DEBUG_TRACE: "true"
  only:
    - master
  tags:
    - ansible
  script:
    - 'ansible-playbook ./ansible/deploy.yml -i ./ansible/hosts -vv'
