---
- name: Set Authorized Key
  authorized_key:
    user: root
    key: "{{ lookup('env', 'SSH_PRIVATE_KEY') }}"

- name: Perform Safe Upgrade
  apt: upgrade=safe update_cache=yes

- import_tasks: hostname.yml
- import_tasks: swap.yml
  when: swap_enabled is defined and swap_enabled == true
