---
- name: Perform Safe Upgrade
  apt: upgrade=safe update_cache=yes

- name: Install depndencies
  apt:
    pkg: '{{ item }}'
    state: present
  with_items:
    - python3-pip

- name: Install pip dependencies
  pip:
    name: '{{ item }}'
  with_items:
    - docker
    - docker-compose

- import_tasks: hostname.yml
- import_tasks: swap.yml
  when: swap_enabled is defined and swap_enabled == true
