---
- name: Add deployment user
  action: 'user name={{ deploy_user }} password={{ deploy_password }} generate_ssh_key=yes shell=/bin/bash'

- name: Add authorized deploy keys
  action: "authorized_key user={{ deploy_user }} key=\"{{ lookup('file', item) }}\""
  with_items: '{{ ssh_public_key_files }}'
